<p class="py-10 m-0">ESTIMADO CLIENTE
    fecha {{$data['fecha']}}
</p>
<p class="">
    RECIBA UN CORDIAL SALUDO POR PARTE DE LA EMPRESA SISTAGUA TECNOLOGÍA EN TRATAMIENTOS DE AGUA, DESEANDOLE QUE SE ENCUENTRE BIEN DE SALUD USTED Y TODA SU FAMILIA.
</p>
<p class="py-10 m-0">
    MEDIANTE EL PRESENTE TENGO EL GRATO DE COMUNICARLE EL REGISTRO DE LA VISITA DE MANTENIMIENTO CORRECTIVO Y PREVENTIVO. PARA MAYOR INFORMACIÓN PUEDE INGRESAR AL SIGUIENTE ENLACE
</p>